image:
  name: kacpak/ubuntu_updated
  username: $DOCKER_USERNAME
  password: $DOCKER_PASSWORD
  email: $DOCKER_EMAIL

pipelines:
  default:
    - step:
        script:
          - echo "Running frontend application build..."
          - cd app
          - npm install --unsafe-perm
          - npm run build
          - echo "You really should run tests for feature branches here... Write them!"
  branches:
    master:
      - step:
          script:
            - echo "Running frontend application build..."
            - cd app
            - npm install --unsafe-perm
            - npm run build
            - cd ..
            - echo "Deploying frontend app..."
            - scp -rpC -P $SSH_PORT app/dist/* $SSH_USERNAME@$SSH_HOSTNAME:$FTP_APP_DIR
            - echo "Deploying backend.."
            - scp -rpC -P $SSH_PORT api/* $SSH_USERNAME@$SSH_HOSTNAME:$FTP_API_DIR
            - ssh $SSH_USERNAME@$SSH_HOSTNAME -p $SSH_PORT "cd $FTP_API_DIR && (composer install || true) && artisan optimize && artisan migrate:refresh --seed"
