cms-memcached:
  image: phpdockerio/memcached:latest
  container_name: cms-memcached

cms-redis:
  image: phpdockerio/redis:latest
  container_name: cms-redis

cms-mysql:
  image: mysql:5.7
  container_name: cms-mysql
  environment:
    - MYSQL_ROOT_PASSWORD=pass
    - MYSQL_DATABASE=cms
    - MYSQL_USER=user
    - MYSQL_PASSWORD=pass

cms-phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: cms-phpmyadmin
  environment:
   - PMA_USER=user
   - PMA_PASSWORD=pass
  ports:
   - "8081:80"
  links:
   - cms-mysql:db

cms-webserver:
  image: phpdockerio/nginx:latest
  container_name: cms-webserver
  volumes:
      - .:/var/www/cms
      - ./docker-config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8080:80"
  links:
   - cms-php

cms-php:
  build: .
  dockerfile: docker-config/php-fpm/Dockerfile
  container_name: cms-php
  volumes:
    - .:/var/www/cms
    - ./docker-config/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  links:
    - cms-memcached
    - cms-mysql
    - cms-redis
